# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Organization Name
# Version: 1.0.0
# Last Modified: 2025-11-02

line-length = 100
src = ["core", "tests", "scripts"]
exclude = [".venv", "build", "dist"]

[lint]
select = ["E", "F", "I", "B", "UP", "PL", "RUF"]
ignore = ["E203"]

[lint.isort]
combine-as-imports = true
known-first-party = ["core"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
